 # To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
|<<<<<<< revert-17-dependabot/npm_and_yarn/actions/glob-0.5.0
  # Enable version updates for tr4200812
|=======
"<<<<<<< dependabot/npm_and_yarn/actions/glob-0.5.0
  # Enable version updates for npm
|<<<<<<< revert-25-dependabot/npm_and_yarn/actions/cache-4.0.3
  - package-ecosystem: 'npm'
|=======
:<<<<<<< 53b4232main
:=======
:=======
  # Enable version updates for tr4200812
》>>>>>>> main
:>>>>>>> main
|>>>>>>> alert-autofix-28
  - package-ecosystem: 'ds'
|>>>>>>> main
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: '/'
    schedule:
      interval: 'weekly'
